### ISSUE TITLE
Help restore the repaired version of ceres-solver

### ISSUE THREAD

**Issue by Heathcliff-saku** [hyeok-jong/hanbok_image#1]
hi！ @hyeok-jong 
I noticed that you emptied the project test4.git, your project is very important for my current research, there are some problems with the original Nerf method of estimating camera poses, can you restore this project please, thanks
![QQ图片20220506160628](https://user-images.githubusercontent.com/55010217/167115742-d504b247-d69f-405c-b10f-668ce97c86f3.png)

**Comment by hyeok-jong** [comment]
@Heathcliff-saku I found the version.  

so you can see [here](https://colab.research.google.com/drive/107a_dVa_XtaulTmkckRYzACNl9NGYgAT?usp=sharing)  

colmap installed successfully and thus `.bin` files created well. 

I recommend fork my repo.

**Comment by Heathcliff-saku** [comment]
@hyeok-jong 
thaaaaanks！ Thank you very much for your timely reply！
